# version: 2
# updates:
#   - package-ecosystem: "npm"
#     directory: "/client/"
#     schedule:
#       interval: "daily"
#     groups:
#       all-dependencies:
#         patterns:
#           - "*"

# Dependabot can't see the requirements.txt for some reason.
# Also, it's only needed for local development because we use AWS Lambda libraries.
# - package-ecosystem: "pip"
#   directory: "/server/"
#   schedule:
#     interval: "daily"
#   groups:
#     all-dependencies:
#       patterns:
#         - "*"
