version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client/"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/server/"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"
