



# TODO - a better method to work out if we need to redeploy
data "archive_file" "website" {
  type        = "zip"
  source_dir  = local.website_dir
  output_path = "${path.root}/website.zip"
  excludes    = [".next", "out", "node_modules"]
}

resource "local_file" "website" {
  content  = <<-EOT
        # This file is automatically generated by terraform
        NEXT_PUBLIC_API_GATEWAY_URL="${data.aws_ssm_parameter.api_gateway_url.value}"
        NEXT_PUBLIC_COGNITO_USER_POOL_ID="${data.aws_ssm_parameter.cognito_user_pool_id.value}"
        NEXT_PUBLIC_COGNITO_CLIENT_ID="${data.aws_ssm_parameter.cognito_client_id.value}"
        NEXT_PUBLIC_COGNITO_REGION="${data.aws_ssm_parameter.cognito_region.value}"
    EOT
  filename = "${local.website_dir}/.env"
}

resource "terraform_data" "build" {
  depends_on = [local_file.website]
  triggers_replace = [
    data.archive_file.website.output_base64sha256
  ]
  provisioner "local-exec" {
    working_dir = local.website_dir
    command     = "npm run build"
  }
}
