output "gateway_url" {
  description = "URL for invoking API Gateway."
  value       = aws_api_gateway_stage.gateway.invoke_url
}

output "cognito_client_id" {
  description = "Client ID for authorising in Cognito."
  value       = local.foundation_output.cognito_client_id
}


resource "local_file" "website" {
  content  = <<-EOT
        # This file is automatically generated by terraform
        NEXT_PUBLIC_API_GATEWAY_URL="${aws_api_gateway_stage.gateway.invoke_url}"
        NEXT_PUBLIC_COGNITO_USER_POOL_ID="${local.foundation_output.cognito_user_pool_id}"
        NEXT_PUBLIC_COGNITO_CLIENT_ID="${local.foundation_output.cognito_client_id}"
        NEXT_PUBLIC_COGNITO_REGION="ap-southeast-2"
    EOT
  filename = "${local.website_dir}/.env"
}

# resource "local_file" "api_tests" {
#   content  = <<-EOT
#         # This file is automatically generated by terraform
#         PYTHONPATH="./lambda/layer/python"
#         API_GATEWAY_URL="${aws_api_gateway_stage.gateway.invoke_url}"
#         COGNITO_USER_POOL="${local.permanent_output.cognito_user_pool_id}"
#         COGNITO_CLIENT_ID="${local.permanent_output.cognito_client_id}"
#         AUTOMATED_TESTER_USERNAME="${local.permanent_output.automated_tester_username}"
#         AUTOMATED_TESTER_PASSWORD="${local.permanent_output.automated_tester_password}"
#     EOT
#   filename = "../../../.env"
# }
