output "gateway_url" {
  description = "URL for invoking API Gateway."
  value       = aws_api_gateway_stage.gateway.invoke_url
}

output "cognito_client_id" {
  description = "Client ID for authorising in Cognito."
  value       = local.foundation_output.cognito_client_id
}

resource "local_file" "website" {
  content  = <<-EOT
        # This file is automatically generated by terraform
        NEXT_PUBLIC_API_GATEWAY_URL="${aws_api_gateway_stage.gateway.invoke_url}"
        NEXT_PUBLIC_COGNITO_USER_POOL_ID="${local.foundation_output.cognito_user_pool_id}"
        NEXT_PUBLIC_COGNITO_CLIENT_ID="${local.foundation_output.cognito_client_id}"
        NEXT_PUBLIC_COGNITO_REGION="ap-southeast-2"
    EOT
  filename = "${local.website_dir}/.env"
}

resource "local_file" "terraform" {
  content  = <<-EOT
        API_GATEWAY_URL=${aws_api_gateway_stage.gateway.invoke_url}
        AUTOMATED_TESTER_USERNAME=${local.automated_tester_username}
        AUTOMATED_TESTER_PASSWORD=${random_password.automated_tester_password.result}
        COGNITO_USER_POOL=${local.foundation_output.cognito_user_pool_id}
        COGNITO_CLIENT_ID=${local.foundation_output.cognito_client_id}
    EOT
  filename = "output.env"
}
