name: "Terraform"

on:
  push:
    branches: ["master"]
  pull_request:

permissions:
  contents: read

jobs:
  # unit_tests:
  #   name: "Unit tests"
  #   runs-on: ubuntu-latest
  #   environment: production
  #   defaults:
  #     run:
  #       shell: bash
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@v4

  #     - name: Setup python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.9"
  #         cache: "pip"
  #         cache-dependency-path: server/requirements.txt

  #     - name: Install server libraries
  #       run: pip install -r server/requirements.txt

  #     - name: Run server unit tests
  #       run: pytest server/tests/unit

  deploy:
    name: "Deploy"
    # needs: [unit_tests]
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialise terraform state
        run: |
          cd terraform/environments/stage/foundation
          terraform init
          terraform plan
