name: "Terraform"

on:
  push:
    branches: ["master"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install server libraries
        run: pip install -r server/requirements.txt

      - name: Run server unit tests
        run: pytest server/tests/unit

  # test:
  #   name: "Test"
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   environment: production
  #   defaults:
  #     run:
  #       shell: bash
  #   steps:
  #     - name: Server unit tests
  #       run: pytest server/tests/unit
