name: "Stage deployment"

on:
  push:
    branches: ["stage"]

permissions:
  contents: read

jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/deployment.yml
    with:
      environment: "stage"
